@echo off
echo Adicionando arquivos ao Git...
git add .
echo Criando o commit...
git commit -m "fix(header): usar PublicHeader em vez de PublicHeaderClient para resolver prop isLoggedIn"
echo Enviando para o GitHub...
git push
echo Concluido!
