@echo off
echo Adicionando arquivos ao Git...
git add .
echo Criando o commit...
git commit -m "fix(build): await params em paginas e route handlers para compatibilidade Next.js 16"
echo Enviando para o GitHub...
git push
echo Concluido!
