@echo off
echo Adicionando arquivos ao Git...
git add .
echo Criando o commit...
git commit -m "fix(mensagens): formatar tipo trucks na pagina de mensagens para compatibilidade TypeScript"
echo Enviando para o GitHub...
git push
echo Concluido!
